language: java
script: make release
before_script:
  - export VERSION=`grep log4jplugin.version plugin.properties | cut -d'=' -f2`
cache:
  directories:
  - "$HOME/.m2"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PBmuG0tqMdgx7wihSh37BWg0JBNbAbj0F1aHsAOsUR6NRQV3Wt8s1V0ocR5Xrt0jJ2BGD2K4IYEu+AE05FSKijzst2K3lWJENN2KuFnwLv9W0LQfcv7MaM18ocSaGyFV83zErKCQbR4VjW8LOXoOs7lLzAll78wvoWPw/446IVBeC1USo6fuO4ojh3/culqzNUKZnnlL0EjalW0h6P0q13D5g38JL5RdTfOpTF/ViwsGswTLtHxn4m3remxmUmBoYytnnM/LCLhT1AHUI9j7aUpIU8W6JZXTMjQf/RvcHT57JByktzipz9RAkIQHfCZLKQI/FTrNmOVFQSgK0W74KXmyIPnQJQTxBKzacjXt8EW6ZflilYsmZJJv5oTrVLuUMyzCHSafTK3vo35vZELLK+PzxG4FYeqZqO3XTHR8feCoyoRThnbRazTy/dMu1cYxrXNzZnJvBkQgBH6eu3LpqrylXM3wAKBP7YG6rXnPWUj9VnnUEvaQ8t3UJQS8p23o2jbZ9S8CQuxx/EVRouIgJe5chNESGiFVz0ZirNYQApMJjXmY9edUUE0JnR0dYZ92Dvuevase8+2/7ZaF4nAvqIW9bI/n61nnBFaHgAyzz4KbJ79+dLX+AjIZpxzK+TbQ1bQVa8zSlO4V8EouZ6AaSXYvYw3oT4GlxRnfc+WiyiI=
  file: release/log4j-plugin-fluency-${VERSION}-jar-with-dependencies.jar
  on:
    tags: true
notifications:
  slack:
    secure: WVBx/OJqLpX9WXyiejEdnOcAf+5ShWJ2gcyeBCX032iKzPphcdPKqH+jnlFaKjqQCZARbRqzlj/if3FZWAlhWtTrWrcY545dRHcsaGvJ/nMtdHlBUuwUNHipSn+RTXtorsYz0efhJMPye2LMl0HgAp3rEs70XUt8rZOwdedLGVgfWRwM+KixhSf8P08v9QjNRNdhWII37KFRdqv/NHryNlVKsTLH6fQOyIvok3vrTvMR8rWMRETXv6JLpCJ3FfOrxo53fW7q+GlXXuVcQ2OGlgxm3eke6q2aXZAqczeB5CSlWgUEA5T3rQ//WI3enwTayRajV/9O26HZvASjSTnDRiSSv1itYqg1Uy6kuJy5ANpBizOyWY6/QTM5Rw00AXvaY9ur0EmyNe5vLNHyTxzdr4R+rXjE07yCDvWM9RGbu+4BipP+mAoJTkuCIP54FWYn1qOJnC8DYywD/+wniCNLbp6yMgbG/aC6H5RmuSy+3xRoEbwvyXKUgA+4gL3I3aAIvidBG+yazRBFvRCn4pUJdTEc4Cpu0jhQWXWyZSE66HNPKyIOXl9JPTzul08MDo9OaqBt+K3yeMVA8EPr196mWLwerF+dExQ2PJhUu/7MAiOgFrIr4/d05iKhj4ivLYBRNN317s2NVo8qyfhPHlfv6PyzhllC/qjClQ2rLOemVhg=
